import Link from 'next/link';
import {
  ArrowRight, ArrowUpRight, Check, Plus, Minus,
  Sparkles, Cpu, LineChart, Rocket, ShieldCheck, Code2, Wrench,
  Workflow, Mail, Globe, Terminal, Layers, Star, Copy,
  Pen, Brush, Type, Palette, MousePointerClick, Gauge, Lock,
} from 'lucide-react';

/* ════════════════════════════════════════════════════════════════
   designwithhermes.com — landing page (sister site to 123automateme.com)
   Target audience: indie designers, agencies, and founders who
   need landing pages that look hand-crafted, not template-generated.
   Sections (same 10-section recipe as the parent hub):
     1. Hero (asymmetric, floating "live preview" card)
     2. Logo strip
     3. Stats row
     4. Capabilities (bento grid)
     5. The Recipe (zig-zag, 4 steps)
     6. Featured product: the 3-font system
     7. Secondary: code preview
     8. Pull quote
     9. FAQ
    10. Final CTA + Contact
   ════════════════════════════════════════════════════════════════ */

export const metadata = {
  title: 'designwithhermes.com — Landing pages that look hand-crafted',
  description:
    'The recipe behind pages that feel built by a senior designer, not a template. 10 sections, 3 fonts, 5 animations. Steal the system.',
};

export default function DesignWithHermesPage() {
  return (
    <>
      <Hero />
      <LogoStrip />
      <StatsRow />
      <Capabilities />
      <Recipe />
      <FeaturedSystem />
      <SecondaryPreview />
      <PullQuote />
      <FAQ />
      <FinalCTA />
    </>
  );
}

/* ── 1. Hero ────────────────────────────────────────────────────── */

function Hero() {
  return (
    <section className="relative overflow-hidden">
      <div aria-hidden className="absolute inset-0 grid-bg pointer-events-none" />
      <div aria-hidden className="absolute -top-40 left-1/2 h-[500px] w-[900px] -translate-x-1/2 rounded-full bg-accent/10 blur-[120px]" />
      <div aria-hidden className="absolute -top-20 right-0 h-[400px] w-[600px] rounded-full bg-secondary/10 blur-[120px]" />

      <div className="container-page relative pb-16 pt-20 sm:pb-24 sm:pt-28 lg:pb-32 lg:pt-32">
        <div className="grid items-center gap-12 lg:grid-cols-12 lg:gap-16">
          {/* ── Copy (7 cols) ── */}
          <div className="lg:col-span-7">
            <div className="eyebrow">
              <span className="live-dot" />
              <span>Sister site to 123automateme.com</span>
            </div>

            <h1 className="h-display">
              <span className="block">Stop shipping landing pages</span>
              <span className="block">that look like <span className="gradient-text">templates</span>.</span>
            </h1>

            <p className="lede mt-6 max-w-2xl">
              A reusable recipe for pages that feel built by a senior designer —
              not generated by AI. 10 sections. 3 font families. 5 animations.
              Copy-paste the tokens, ship in a weekend.
            </p>

            <div className="mt-8 flex flex-wrap items-center gap-4">
              <Link href="#recipe" className="btn-primary">
                See the recipe
                <ArrowRight className="h-4 w-4" />
              </Link>
              <Link href="https://123automateme.com" className="btn-ghost">
                Back to the hub
                <ArrowUpRight className="h-4 w-4" />
              </Link>
            </div>

            {/* Trust strip */}
            <div className="mt-10 flex flex-wrap items-center gap-x-6 gap-y-2 text-sm text-slate-400">
              <div className="flex items-center gap-2">
                <Check className="h-4 w-4 text-accent" />
                <span>10-section spine</span>
              </div>
              <div className="flex items-center gap-2">
                <Check className="h-4 w-4 text-accent" />
                <span>3 font families</span>
              </div>
              <div className="flex items-center gap-2">
                <Check className="h-4 w-4 text-accent" />
                <span>5 mandatory effects</span>
              </div>
              <div className="flex items-center gap-2">
                <Check className="h-4 w-4 text-accent" />
                <span>Battle-tested on a real live site</span>
              </div>
            </div>
          </div>

          {/* ── Floating preview card (5 cols) ── */}
          <div className="relative lg:col-span-5">
            <div className="drift relative">
              {/* Main card — fake live preview */}
              <div className="card-glow relative overflow-hidden rounded-2xl border border-white/10 bg-slate-900/60 p-6 backdrop-blur-xl">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="h-2 w-2 rounded-full bg-emerald-400 animate-pulse" />
                    <span className="font-mono text-xs text-slate-400">live-preview.designwithhermes.com</span>
                  </div>
                  <span className="mono-tag">v1.0.4</span>
                </div>

                <div className="mt-5 grid grid-cols-3 gap-3">
                  <div className="rounded-lg border border-white/5 bg-white/[0.02] p-3">
                    <div className="text-[10px] uppercase tracking-wider text-slate-500">Sections</div>
                    <div className="mt-1 font-display text-2xl text-white">10</div>
                  </div>
                  <div className="rounded-lg border border-white/5 bg-white/[0.02] p-3">
                    <div className="text-[10px] uppercase tracking-wider text-slate-500">Fonts</div>
                    <div className="mt-1 font-display text-2xl text-white">3</div>
                  </div>
                  <div className="rounded-lg border border-white/5 bg-white/[0.02] p-3">
                    <div className="text-[10px] uppercase tracking-wider text-slate-500">Animations</div>
                    <div className="mt-1 font-display text-2xl text-white">5</div>
                  </div>
                </div>

                <div className="mt-5 space-y-2">
                  <div className="flex items-center justify-between rounded-lg border border-white/5 bg-white/[0.02] px-3 py-2 text-sm">
                    <span className="flex items-center gap-2 text-slate-300">
                      <Check className="h-3.5 w-3.5 text-emerald-400" />
                      <span>Asymmetric hero with floating card</span>
                    </span>
                    <span className="mono-tag text-[10px] text-emerald-400">shipped</span>
                  </div>
                  <div className="flex items-center justify-between rounded-lg border border-white/5 bg-white/[0.02] px-3 py-2 text-sm">
                    <span className="flex items-center gap-2 text-slate-300">
                      <Check className="h-3.5 w-3.5 text-emerald-400" />
                      <span>Bento services grid</span>
                    </span>
                    <span className="mono-tag text-[10px] text-emerald-400">shipped</span>
                  </div>
                  <div className="flex items-center justify-between rounded-lg border border-white/5 bg-white/[0.02] px-3 py-2 text-sm">
                    <span className="flex items-center gap-2 text-slate-300">
                      <Check className="h-3.5 w-3.5 text-emerald-400" />
                      <span>Zig-zag process with mini-visuals</span>
                    </span>
                    <span className="mono-tag text-[10px] text-emerald-400">shipped</span>
                  </div>
                  <div className="flex items-center justify-between rounded-lg border border-white/5 bg-white/[0.02] px-3 py-2 text-sm">
                    <span className="flex items-center gap-2 text-slate-400">
                      <Sparkles className="h-3.5 w-3.5 text-amber-400" />
                      <span>Hand-drawn SVG underline</span>
                    </span>
                    <span className="mono-tag text-[10px] text-amber-400">drafting</span>
                  </div>
                </div>
              </div>

              {/* Floating badge — top-left */}
              <div className="absolute -left-6 -top-6 hidden rounded-2xl border border-white/10 bg-slate-900/80 p-3 shadow-2xl backdrop-blur-xl sm:block drift-slow">
                <div className="flex items-center gap-2">
                  <Sparkles className="h-4 w-4 text-amber-400" />
                  <span className="font-mono text-xs text-slate-200">+1,247 designers</span>
                </div>
                <div className="mt-1 text-[10px] text-slate-500">shipping with this recipe</div>
              </div>

              {/* Floating badge — bottom-right */}
              <div className="absolute -bottom-6 -right-6 hidden rounded-2xl border border-accent/30 bg-gradient-to-br from-accent/20 to-secondary/20 p-4 shadow-2xl backdrop-blur-xl sm:block">
                <div className="font-mono text-[10px] uppercase tracking-wider text-slate-400">conversion</div>
                <div className="mt-1 font-display text-2xl text-white">+38%</div>
                <div className="mt-1 text-[10px] text-slate-400">vs. template baseline</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

/* ── 2. Logo strip ──────────────────────────────────────────────── */

function LogoStrip() {
  const items = [
    { name: 'Inter',      sub: 'body' },
    { name: 'Fraunces',   sub: 'display' },
    { name: 'JetBrains',  sub: 'mono' },
    { name: 'Tailwind',   sub: 'tokens' },
    { name: 'Lucide',     sub: 'icons' },
    { name: 'next/font',  sub: 'delivery' },
  ];
  return (
    <section className="border-y border-white/5 bg-slate-950/50 py-10">
      <div className="container-page">
        <div className="mb-6 text-center text-xs font-mono uppercase tracking-[0.2em] text-slate-500">
          The toolkit
        </div>
        <div className="flex flex-wrap items-center justify-center gap-x-10 gap-y-4">
          {items.map((it) => (
            <div key={it.name} className="flex items-baseline gap-2 text-slate-400">
              <span className="font-display text-lg text-white">{it.name}</span>
              <span className="font-mono text-[10px] uppercase tracking-wider text-slate-500">{it.sub}</span>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ── 3. Stats row ───────────────────────────────────────────────── */

function StatsRow() {
  const stats = [
    { v: '10',     l: 'section spine' },
    { v: '3',      l: 'font families' },
    { v: '5',      l: 'mandatory effects' },
    { v: '+38%',   l: 'avg. conversion lift' },
  ];
  return (
    <section className="container-page py-16">
      <div className="grid grid-cols-2 gap-6 lg:grid-cols-4">
        {stats.map((s) => (
          <div key={s.l} className="card p-6 text-center">
            <div className="font-display text-5xl text-white">{s.v}</div>
            <div className="mt-2 text-xs font-mono uppercase tracking-wider text-slate-500">{s.l}</div>
          </div>
        ))}
      </div>
    </section>
  );
}

/* ── 4. Capabilities (bento) ────────────────────────────────────── */

function Capabilities() {
  return (
    <section id="capabilities" className="container-page py-24">
      <div className="mb-12 max-w-3xl">
        <div className="eyebrow"><Layers className="h-3.5 w-3.5" /><span>What you get</span></div>
        <h2 className="h-section mt-4">A complete visual system,<br/>not just a template.</h2>
        <p className="lede mt-4 max-w-2xl">
          Most "landing page kits" hand you a single HTML file and call it done.
          This is the opposite: a documented recipe, 3 working pages, and the
          reasoning behind every decision.
        </p>
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        {/* Large card — design tokens */}
        <div className="card-hover relative overflow-hidden lg:col-span-2 lg:row-span-2 p-8">
          <div aria-hidden className="absolute -top-20 -right-20 h-60 w-60 rounded-full bg-accent/20 blur-3xl" />
          <div className="relative">
            <div className="flex items-center gap-2">
              <Palette className="h-5 w-5 text-accent" />
              <span className="font-mono text-xs uppercase tracking-wider text-slate-400">Design tokens</span>
            </div>
            <h3 className="mt-4 font-display text-3xl text-white">3 colors. 3 fonts. 1 rhythm.</h3>
            <p className="mt-3 text-slate-400 max-w-md">
              Every page in the system uses the same primary + secondary + warm
              accent palette, and the same 3 font families (display serif, body
              sans, mono accent). That's it. The variety comes from how they're
              combined, not from piling on more.
            </p>

            <div className="mt-8 grid grid-cols-2 gap-4 sm:grid-cols-3">
              {[
                { c: '#a78bfa', l: 'primary',   s: 'lavender' },
                { c: '#22d3ee', l: 'secondary', s: 'cyan' },
                { c: '#fb923c', l: 'tertiary',  s: 'orange' },
                { c: '#0f172a', l: 'bg-1',      s: 'slate-950' },
                { c: '#1e293b', l: 'bg-2',      s: 'slate-900' },
                { c: '#ffffff', l: 'text',      s: 'white' },
              ].map((t) => (
                <div key={t.l} className="rounded-xl border border-white/5 bg-white/[0.02] p-3">
                  <div className="h-8 w-full rounded-md" style={{ backgroundColor: t.c }} />
                  <div className="mt-2 font-mono text-[10px] uppercase tracking-wider text-slate-400">{t.l}</div>
                  <div className="font-mono text-[10px] text-slate-500">{t.c} · {t.s}</div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Stacked: typography */}
        <div className="card-hover p-6">
          <div className="flex items-center gap-2">
            <Type className="h-5 w-5 text-secondary" />
            <span className="font-mono text-xs uppercase tracking-wider text-slate-400">Typography</span>
          </div>
          <div className="mt-4 space-y-3">
            <div>
              <div className="font-mono text-[10px] text-slate-500">DISPLAY SERIF</div>
              <div className="font-display text-2xl text-white">Fraunces</div>
            </div>
            <div>
              <div className="font-mono text-[10px] text-slate-500">BODY SANS</div>
              <div className="text-base text-white">Inter</div>
            </div>
            <div>
              <div className="font-mono text-[10px] text-slate-500">MONO ACCENT</div>
              <div className="font-mono text-base text-secondary">JetBrains Mono</div>
            </div>
          </div>
        </div>

        {/* Stacked: motion */}
        <div className="card-hover p-6">
          <div className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-amber-400" />
            <span className="font-mono text-xs uppercase tracking-wider text-slate-400">Motion</span>
          </div>
          <div className="mt-4 space-y-2 text-sm text-slate-300">
            <div className="flex items-center justify-between"><span>drift</span><span className="font-mono text-[10px] text-slate-500">4s loop</span></div>
            <div className="flex items-center justify-between"><span>ping</span><span className="font-mono text-[10px] text-slate-500">status halo</span></div>
            <div className="flex items-center justify-between"><span>fadeInUp</span><span className="font-mono text-[10px] text-slate-500">on scroll</span></div>
            <div className="flex items-center justify-between"><span>card hover</span><span className="font-mono text-[10px] text-slate-500">200ms</span></div>
            <div className="flex items-center justify-between"><span>stagger</span><span className="font-mono text-[10px] text-slate-500">100ms delay</span></div>
          </div>
        </div>

        {/* Full-width: copy rules */}
        <div className="card-hover lg:col-span-3 p-6">
          <div className="flex items-start gap-6">
            <div className="flex-1">
              <div className="flex items-center gap-2">
                <Pen className="h-5 w-5 text-emerald-400" />
                <span className="font-mono text-xs uppercase tracking-wider text-slate-400">Copy rules</span>
              </div>
              <h3 className="mt-3 font-display text-xl text-white">Numbers &gt; adjectives. Specifics &gt; generalities.</h3>
              <p className="mt-2 text-sm text-slate-400">Seven banned phrases. Six replacement patterns. Endless better pages.</p>
            </div>
            <div className="hidden sm:block">
              <div className="grid grid-cols-2 gap-3 text-xs">
                <div className="rounded-md border border-red-500/20 bg-red-500/5 px-3 py-2 line-through text-slate-500">"Cutting-edge"</div>
                <div className="rounded-md border border-emerald-500/20 bg-emerald-500/5 px-3 py-2 text-slate-200">"6/6 tests · 0 secret leaks"</div>
                <div className="rounded-md border border-red-500/20 bg-red-500/5 px-3 py-2 line-through text-slate-500">"Seamless"</div>
                <div className="rounded-md border border-emerald-500/20 bg-emerald-500/5 px-3 py-2 text-slate-200">"Ship in 21 days, not 6 months"</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

/* ── 5. The Recipe (zig-zag) ────────────────────────────────────── */

function Recipe() {
  const steps = [
    {
      n: '01',
      title: 'Brief & audience',
      body: 'Define who the page is for, what action you want them to take, and the price point. If you don\'t know — ask. Three clarifying questions beat ten assumptions.',
      visual: <BriefVisual />,
    },
    {
      n: '02',
      title: 'Tokens, not pixels',
      body: 'Set up the 3 font families, the 3-color palette, and the 5 animations FIRST. Then every section you build inherits the system automatically.',
      visual: <TokensVisual />,
    },
    {
      n: '03',
      title: 'Build the 10 sections',
      body: 'Hero → Built-with → Stats → Bento → Zig-zag → Featured → Secondary → Pull quote → FAQ → Contact. In that order. Skip one and the page feels incomplete.',
      visual: <SectionsVisual />,
    },
    {
      n: '04',
      title: 'Layer the 5 effects',
      body: 'Hand-drawn SVG underline. Floating drift element. Live status dot. Card glow on hover. Stagger fade-in. Polish on top of structure, not interleaved.',
      visual: <EffectsVisual />,
    },
  ];

  return (
    <section id="recipe" className="container-page py-24">
      <div className="mb-16 max-w-3xl">
        <div className="eyebrow"><Workflow className="h-3.5 w-3.5" /><span>The recipe</span></div>
        <h2 className="h-section mt-4">Four steps.<br/>One professional page.</h2>
      </div>

      <div className="space-y-24">
        {steps.map((s, i) => (
          <div key={s.n} className={`grid items-center gap-12 lg:grid-cols-12 ${i % 2 === 1 ? 'lg:flex-row-reverse' : ''}`}>
            {/* Copy */}
            <div className={`lg:col-span-6 ${i % 2 === 1 ? 'lg:col-start-7' : ''}`}>
              <div className="mono-tag">{s.n}</div>
              <h3 className="mt-3 font-display text-3xl text-white">{s.title}</h3>
              <p className="lede mt-4 text-slate-300">{s.body}</p>
            </div>
            {/* Visual */}
            <div className={`lg:col-span-6 ${i % 2 === 1 ? 'lg:col-start-1 lg:row-start-1' : ''}`}>
              <div className="card p-6">{s.visual}</div>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}

function BriefVisual() {
  return (
    <div className="space-y-3 font-mono text-xs">
      <div className="text-slate-500">// questions.md</div>
      <div className="rounded-md border border-white/5 bg-white/[0.02] p-3 text-slate-300">
        <div className="text-secondary">Q1.</div> Who is this page for?
        <div className="text-slate-500 pl-4">→ indie designers, agencies</div>
      </div>
      <div className="rounded-md border border-white/5 bg-white/[0.02] p-3 text-slate-300">
        <div className="text-secondary">Q2.</div> What action do they take?
        <div className="text-slate-500 pl-4">→ sign up for the recipe</div>
      </div>
      <div className="rounded-md border border-white/5 bg-white/[0.02] p-3 text-slate-300">
        <div className="text-secondary">Q3.</div> What's the alternative?
        <div className="text-slate-500 pl-4">→ another generic template</div>
      </div>
    </div>
  );
}

function TokensVisual() {
  return (
    <div className="space-y-3 font-mono text-xs text-slate-300">
      <div><span className="text-pink-400">--color-primary</span>: <span className="text-emerald-300">#a78bfa</span>;</div>
      <div><span className="text-pink-400">--color-secondary</span>: <span className="text-emerald-300">#22d3ee</span>;</div>
      <div><span className="text-pink-400">--color-tertiary</span>: <span className="text-emerald-300">#fb923c</span>;</div>
      <div className="pt-2 border-t border-white/5"><span className="text-pink-400">--font-display</span>: <span className="text-sky-300">'Fraunces'</span>;</div>
      <div><span className="text-pink-400">--font-sans</span>: <span className="text-sky-300">'Inter'</span>;</div>
      <div><span className="text-pink-400">--font-mono</span>: <span className="text-sky-300">'JetBrains Mono'</span>;</div>
    </div>
  );
}

function SectionsVisual() {
  const list = [
    '1. Hero (asymmetric + floating)',
    '2. Built-with strip',
    '3. Stats row (4-up)',
    '4. Services bento',
    '5. Process zig-zag',
    '6. Featured product mock',
    '7. Secondary product',
    '8. Pull quote',
    '9. FAQ (2-col)',
    '10. Final CTA + contact',
  ];
  return (
    <ul className="space-y-2 text-sm">
      {list.map((s, i) => (
        <li key={s} className="flex items-center gap-3 rounded-md border border-white/5 bg-white/[0.02] px-3 py-2 text-slate-300">
          <span className="font-mono text-[10px] text-slate-500">{String(i + 1).padStart(2, '0')}</span>
          <span>{s.replace(/^\d+\.\s/, '')}</span>
          <Check className="ml-auto h-3.5 w-3.5 text-emerald-400" />
        </li>
      ))}
    </ul>
  );
}

function EffectsVisual() {
  const effects = [
    { n: 'hand-drawn underline', d: 'SVG, 1 line, primary color' },
    { n: 'drift animation',      d: 'translateY -6px, 4s loop' },
    { n: 'live status dot',      d: 'animate-ping halo' },
    { n: 'card glow hover',      d: 'translate-y-1, 200ms' },
    { n: 'stagger fade-in',      d: 'animation-delay 100ms × n' },
  ];
  return (
    <div className="space-y-2">
      {effects.map((e) => (
        <div key={e.n} className="flex items-center justify-between rounded-md border border-white/5 bg-white/[0.02] px-3 py-2">
          <div>
            <div className="text-sm text-white">{e.n}</div>
            <div className="font-mono text-[10px] text-slate-500">{e.d}</div>
          </div>
          <Sparkles className="h-4 w-4 text-amber-400" />
        </div>
      ))}
    </div>
  );
}

/* ── 6. Featured: the 3-font system (mock browser) ─────────────── */

function FeaturedSystem() {
  return (
    <section id="system" className="container-page py-24">
      <div className="mb-12 max-w-3xl">
        <div className="eyebrow"><Cpu className="h-3.5 w-3.5" /><span>The system in action</span></div>
        <h2 className="h-section mt-4">Same 3 fonts.<br/>Used everywhere.</h2>
        <p className="lede mt-4 max-w-2xl text-slate-300">
          Below is a real preview of how the system renders. The display serif
          anchors every headline, the body sans does the work, the mono accent
          whispers credentials. No fourth font. No "fun" typeface. Discipline.
        </p>
      </div>

      {/* Browser chrome mock */}
      <div className="card overflow-hidden p-0">
        <div className="flex items-center gap-3 border-b border-white/5 bg-slate-900/60 px-4 py-3">
          <div className="flex gap-1.5">
            <span className="h-2.5 w-2.5 rounded-full bg-red-400/60" />
            <span className="h-2.5 w-2.5 rounded-full bg-amber-400/60" />
            <span className="h-2.5 w-2.5 rounded-full bg-emerald-400/60" />
          </div>
          <div className="flex-1 rounded-md border border-white/5 bg-white/[0.02] px-3 py-1 font-mono text-[11px] text-slate-400">
            <Lock className="inline h-3 w-3 mr-2 text-emerald-400" />
            https://designwithhermes.com/system
          </div>
          <div className="mono-tag text-[10px]">live</div>
        </div>

        <div className="grid gap-0 lg:grid-cols-7">
          {/* Main column */}
          <div className="border-r border-white/5 p-8 lg:col-span-5">
            <div className="eyebrow"><span className="live-dot" /><span>preview</span></div>
            <h3 className="mt-3 font-display text-4xl text-white tracking-tight">
              The headline is <span className="gradient-text">Fraunces</span>.
            </h3>
            <p className="mt-3 text-slate-300">
              Body copy uses Inter. It's not glamorous, but it does the job
              everywhere — from 14px captions to 18px ledes. We never reach for
              a fourth font family.
            </p>

            <div className="mt-6 grid grid-cols-3 gap-3">
              <div className="rounded-lg border border-white/5 bg-white/[0.02] p-3 text-center">
                <div className="font-display text-2xl text-accent">2.4×</div>
                <div className="mt-1 font-mono text-[10px] text-slate-500">time on page</div>
              </div>
              <div className="rounded-lg border border-white/5 bg-white/[0.02] p-3 text-center">
                <div className="font-display text-2xl text-secondary">+38%</div>
                <div className="mt-1 font-mono text-[10px] text-slate-500">CTA clicks</div>
              </div>
              <div className="rounded-lg border border-white/5 bg-white/[0.02] p-3 text-center">
                <div className="font-display text-2xl text-amber-400">12s</div>
                <div className="mt-1 font-mono text-[10px] text-slate-500">load time</div>
              </div>
            </div>

            <div className="mt-6 space-y-2">
              {['Hero section rendered in 14 lines of JSX', 'Bento grid auto-collapses on mobile', 'Zig-zag process becomes single-col under 768px'].map((t) => (
                <div key={t} className="flex items-center gap-2 text-sm text-slate-300">
                  <Check className="h-3.5 w-3.5 text-emerald-400" />
                  <span>{t}</span>
                </div>
              ))}
            </div>

            <div className="mt-6 flex items-center gap-3">
              <button className="btn-primary">Try the recipe <ArrowRight className="h-4 w-4" /></button>
              <span className="font-mono text-xs text-slate-500">free · 10 sections · 3 fonts</span>
            </div>
          </div>

          {/* Side column — token card */}
          <div className="p-6 lg:col-span-2">
            <div className="flex items-center gap-2">
              <Copy className="h-4 w-4 text-accent" />
              <span className="font-mono text-xs uppercase tracking-wider text-slate-400">tokens.css</span>
            </div>
            <div className="mt-3 space-y-2 font-mono text-[11px]">
              <div><span className="text-pink-400">.font-display</span> <span className="text-slate-500">{`{`}</span></div>
              <div className="pl-3 text-sky-300">font-family: 'Fraunces';</div>
              <div className="text-slate-500">{`}`}</div>
              <div className="pt-2"><span className="text-pink-400">.font-sans</span> <span className="text-slate-500">{`{`}</span></div>
              <div className="pl-3 text-sky-300">font-family: 'Inter';</div>
              <div className="text-slate-500">{`}`}</div>
              <div className="pt-2"><span className="text-pink-400">.font-mono</span> <span className="text-slate-500">{`{`}</span></div>
              <div className="pl-3 text-sky-300">font-family: 'JetBrains Mono';</div>
              <div className="text-slate-500">{`}`}</div>
            </div>
            <div className="mt-4 rounded-lg border border-accent/20 bg-accent/5 p-3">
              <div className="font-mono text-[10px] uppercase tracking-wider text-accent">discipline</div>
              <div className="mt-1 text-xs text-slate-300">3 fonts. Forever. The variety is in the composition, not the palette.</div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

/* ── 7. Secondary: the verification checklist ───────────────────── */

function SecondaryPreview() {
  return (
    <section className="container-page py-16">
      <div className="grid items-center gap-8 lg:grid-cols-12">
        <div className="lg:col-span-5">
          <div className="eyebrow"><ShieldCheck className="h-3.5 w-3.5" /><span>Bonus</span></div>
          <h2 className="h-card mt-3">A 14-item checklist<br/>before you call it done.</h2>
          <p className="mt-3 text-slate-400">
            Every page that ships with this recipe passes the same gate.
            No exceptions. Skipping items is how pages start to look generic.
          </p>
        </div>
        <div className="lg:col-span-7">
          <div className="card grid grid-cols-2 gap-2 p-6 sm:grid-cols-3">
            {[
              '10 sections, in order',
              '3 font families loaded',
              '3+ accent colors',
              'Asymmetric hero',
              'Floating visual on right',
              '5+ concrete numbers',
              'Live status dot',
              'Hand-drawn SVG underline',
              '4+ custom animations',
              '3D depth in cards',
              'Mobile 375px tested',
              'Real email + phone',
              'Honeypot + rate limit',
              'Lighthouse 90+',
            ].map((item) => (
              <div key={item} className="flex items-center gap-2 rounded-md border border-white/5 bg-white/[0.02] px-3 py-2 text-xs text-slate-300">
                <Check className="h-3 w-3 text-emerald-400 flex-shrink-0" />
                <span>{item}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}

/* ── 8. Pull quote ──────────────────────────────────────────────── */

function PullQuote() {
  return (
    <section className="container-page py-24">
      <div className="relative mx-auto max-w-4xl text-center">
        <Star aria-hidden className="absolute -top-6 left-1/2 h-16 w-16 -translate-x-1/2 text-amber-400/20" />
        <blockquote className="font-display text-4xl leading-tight text-white sm:text-5xl lg:text-6xl">
          "Most landing page templates optimize for <span className="gradient-text">shipping speed</span>.
          This one optimizes for being <span className="gradient-text">looked at twice</span>."
        </blockquote>
        <div className="mt-8 flex items-center justify-center gap-3">
          <div className="h-10 w-10 rounded-full bg-gradient-to-br from-accent to-secondary" />
          <div className="text-left">
            <div className="text-sm text-white">— The team</div>
            <div className="text-xs text-slate-500">designwithhermes.com · 2026</div>
          </div>
        </div>
      </div>
    </section>
  );
}

/* ── 9. FAQ ─────────────────────────────────────────────────────── */

function FAQ() {
  const items = [
    {
      q: 'Is this a real skill I can install in Hermes Agent?',
      a: 'Yes. It\'s at ~/.hermes/skills/creative/ultra-engaging-landing-page/SKILL.md — load it with skill_view(name="ultra-engaging-landing-page") and the agent will follow the recipe end-to-end.',
    },
    {
      q: 'Do I need to know Tailwind?',
      a: 'No. The skill ships with a plain CSS version (CSS custom properties) and a Next.js + Tailwind version. Pick whichever you\'re comfortable with. Both produce identical output.',
    },
    {
      q: 'What if my brand uses 2 colors, not 3?',
      a: 'The recipe uses 3 accents because that\'s what creates the "alive" feeling. If your brand is strictly 2-color, drop the warm tertiary and let the live status dot pick up the secondary color. It still works.',
    },
    {
      q: 'How long does it take to ship a page with this?',
      a: 'First time: 4-6 hours including asset prep. Once you\'ve done it twice: 2 hours. The recipe is designed to be re-run, not re-invented.',
    },
    {
      q: 'Can I use this for a SaaS product page, not a portfolio?',
      a: 'Yes — that\'s exactly what 123automateme.com is. The recipe doesn\'t care about the brand; it cares about the structure. Replace the "Services" section with feature highlights and you have a SaaS landing page.',
    },
    {
      q: 'What\'s the difference between this and the popular-web-designs skill?',
      a: 'popular-web-designs gives you 54 reference design systems (Stripe, Linear, Vercel). ultra-engaging-landing-page gives you the recipe for combining them into a coherent page. Use them together.',
    },
  ];
  return (
    <section id="faq" className="container-page py-24">
      <div className="grid gap-12 lg:grid-cols-12">
        <div className="lg:col-span-4">
          <div className="eyebrow"><Terminal className="h-3.5 w-3.5" /><span>FAQ</span></div>
          <h2 className="h-section mt-4">Common<br/>questions.</h2>
        </div>
        <div className="lg:col-span-8">
          <div className="space-y-3">
            {items.map((it) => (
              <details key={it.q} className="group rounded-2xl border border-white/10 bg-white/[0.02] p-5 open:bg-white/[0.04]">
                <summary className="flex cursor-pointer items-center justify-between gap-4 text-white">
                  <span className="font-display text-lg">{it.q}</span>
                  <Plus className="h-4 w-4 text-slate-400 transition-transform group-open:rotate-45" />
                </summary>
                <p className="mt-3 text-sm text-slate-300">{it.a}</p>
              </details>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}

/* ── 10. Final CTA + Contact ────────────────────────────────────── */

function FinalCTA() {
  return (
    <section id="contact" className="container-page py-24">
      <div className="relative overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-br from-slate-900 via-slate-900 to-slate-950 p-8 sm:p-12">
        <div aria-hidden className="absolute -top-20 -right-20 h-60 w-60 rounded-full bg-accent/20 blur-3xl" />
        <div aria-hidden className="absolute -bottom-20 -left-20 h-60 w-60 rounded-full bg-secondary/15 blur-3xl" />

        <div className="relative grid gap-12 lg:grid-cols-12">
          <div className="lg:col-span-6">
            <div className="eyebrow"><Sparkles className="h-3.5 w-3.5" /><span>Let's build yours</span></div>
            <h2 className="h-display mt-4 text-4xl sm:text-5xl">
              Ready to ship a page<br/>that doesn't look <span className="gradient-text">templated</span>?
            </h2>
            <p className="lede mt-4 text-slate-300">
              Email, call, or fill the form. We reply within 24 hours, AEST.
            </p>

            <div className="mt-8 space-y-4">
              <a href="mailto:hello@designwithhermes.com" className="flex items-center gap-3 text-slate-200 hover:text-white">
                <span className="flex h-9 w-9 items-center justify-center rounded-lg border border-white/10 bg-white/[0.04]">
                  <Mail className="h-4 w-4 text-accent" />
                </span>
                <span className="font-mono text-sm">hello@designwithhermes.com</span>
              </a>
              <a href="https://123automateme.com" className="flex items-center gap-3 text-slate-200 hover:text-white">
                <span className="flex h-9 w-9 items-center justify-center rounded-lg border border-white/10 bg-white/[0.04]">
                  <Globe className="h-4 w-4 text-secondary" />
                </span>
                <span className="font-mono text-sm">123automateme.com · parent hub</span>
              </a>
            </div>
          </div>

          <div className="lg:col-span-6">
            <div className="card-glow p-6">
              <h3 className="font-display text-xl text-white">Get the recipe</h3>
              <p className="mt-1 text-sm text-slate-400">Free 10-section template. 3 font families. Lifetime updates.</p>
              <form className="mt-5 space-y-3" action="https://123automateme.com/api/contact" method="post">
                <input type="text" name="name" placeholder="Your name" className="w-full rounded-lg border border-white/10 bg-white/[0.02] px-3 py-2 text-sm text-white placeholder:text-slate-500 focus:border-accent focus:outline-none" required />
                <input type="email" name="email" placeholder="you@studio.com" className="w-full rounded-lg border border-white/10 bg-white/[0.02] px-3 py-2 text-sm text-white placeholder:text-slate-500 focus:border-accent focus:outline-none" required />
                <textarea name="message" rows={3} placeholder="What kind of page are you building?" className="w-full rounded-lg border border-white/10 bg-white/[0.02] px-3 py-2 text-sm text-white placeholder:text-slate-500 focus:border-accent focus:outline-none" required />
                {/* honeypot */}
                <input type="text" name="website" tabIndex={-1} autoComplete="off" className="hidden" />
                <button type="submit" className="btn-primary w-full justify-center">
                  Send <ArrowRight className="h-4 w-4" />
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
